Feature/vee validate
NielsOuvrard/Projet-stage-Vue-3 pull request #2
Opened 2022-07-27 14:55 UTC by gabrielmorais4

ogin and registratrion page using veeValidade, css and 2 new components, one to handle the text inputs and the othe one is to handle the password input. The error messages are the same! Going to do a personalized ones after

2022-07-27 17:44 UTC, Pandazaur requested changes

2022-07-27 17:44 UTC, Pandazaur commented on src/components/MyPasswordInput .vue
> +        <div v-if="register" class="input__password">
C'est un peu étrange de devoir passer un `register` pour afficher le second input. C'est pas le rôle de l'input de faire ça.

Attention il y a l'air d'y avoir un `<espace>` à la fin du fichier

2022-07-27 17:44 UTC, Pandazaur commented on src/components/NavbarLink.vue
> +            font-size: 15px;
Des `em` par des `px`

2022-07-27 17:44 UTC, Pandazaur commented on src/components/NavbarLink.vue
> +                font-size: 20px;
Des `em` par des `px`

2022-07-27 17:44 UTC, Pandazaur commented on src/views/RegisterView.vue
> +    import MyPasswordInputVue from '../components/MyPasswordInput .vue'
```suggestion
    import MyPasswordInputVue from '../components/MyPasswordInput.vue'
```

2022-07-27 18:10 UTC, gabrielmorais4 commented on src/components/MyPasswordInput .vue
> +        <div v-if="register" class="input__password">
c'est parce que j'utilise également MyPasswordInput lors de la connexion, donc j'envoie les props 'register' pour ne pas afficher le deuxième input lors de la connexion et uniquement lors de l'enregistrement

2022-07-28 08:41 UTC, kevbesset commented on src/components/GlobalNavbar.vue
> +    }
A mettre plutôt directement dans le block css de la classe pour éviter de diviser le code d'une meme classe

donc par exemple 
```scss
.navbar {
  ... les styles ici

  @media (min-width: 5em) {
    flex-direction: row;
    padding: 1em;
  }
}
```

2022-07-28 08:41 UTC, kevbesset commented on src/components/MyPasswordInput.vue
> +            <Field
J'ai zappé lors de la précédente review mais il faut qu'un composant Vue soit en - au moins - 2 mots clefs, donc ici par exemple `FormField` plutôt. C'est une bonne pratique recommandé par Vue

2022-07-28 08:41 UTC, kevbesset commented on src/components/MyPasswordInput.vue
> +                :placeholder="`${t(`signUp.password`)}`"
pas besoin de l'entourer d'un template string (backquote + ${...})

2022-07-28 08:41 UTC, kevbesset commented on src/components/MyPasswordInput.vue
> +                class="input__password__field"
attention en BEM tu ne peux qu'avoir le BLOCK (input) et un ELEMENT (password) mais pas de sous-element (field).

Donc par exemple `input__field`, c'est pour éviter trop de nesting ensuite dans le scss

2022-07-28 08:41 UTC, kevbesset commented on src/components/GlobalNavbar.vue
> +    }
À revoir aussi les autres endroits où tu as fais tes media query comme ça

2022-07-28 08:41 UTC, kevbesset commented on src/components/MyPasswordInput.vue
> +-->
pas besoin de ça ahah

2022-07-28 13:15 UTC, kevbesset approved these changes

2022-07-28 13:18 UTC, merged