users features
NielsOuvrard/Projet-stage-Vue-3 pull request #3
Opened 2022-07-28 15:33 UTC by gabrielmorais4

registration and connection using pinia and local storage, user connection(check if the account exists) and registration(check if the email is already in use) validation, reactive navbar depending on if u are connected or not and logout functionality

2022-07-28 15:37 UTC, kevbesset commented on src/components/NavbarLink.vue
> +    }
au final ça pourrait être une computed plutôt qu'une méthode, non?

2022-07-28 15:40 UTC, Pandazaur commented on src/components/NavbarLink.vue
> +    }
Ca pourrait aussi être un computer/getter Pinia aussi

2022-07-28 15:48 UTC, Pandazaur requested changes

2022-07-28 15:48 UTC, Pandazaur commented on src/components/NavbarLink.vue
> +            {{ t(props.link) }}
On utilise pas les "props" dans la partie "template"

2022-07-28 15:48 UTC, Pandazaur commented on src/store/userStore.ts
> +    users: Registered[] | null
Vous initialisez votre store avec un tableau dans tous les cas, donc je pense pas que va soit nécessaire d'ajouter le type `null` pour `users`

2022-07-28 15:48 UTC, Pandazaur commented on src/views/LoginView.vue
> +            store.users?.filter((user) => {
Vous pouvez plutôt utiliser `.find()` ou `.some()` pour éviter d'aller jusqu'au bout du tableau si vous trouvez un user qui a un compte

2022-07-28 15:48 UTC, Pandazaur commented on src/views/LoginView.vue
> +            store.users?.filter((user) => {
Optionnel: Ca peut être bien de sortir aussi cette partie dans une variable pour la lisibilité du code

2022-07-28 15:48 UTC, Pandazaur commented on src/views/LoginView.vue
> +            store.setUserConnecting(userConnecting as Logged)
Tu ne devrais pas avoir à forcer le type ici, tu peux le passer dans:
```
handleSubmit((userConnecting: Logged, actions) => {
```

2022-07-28 15:48 UTC, Pandazaur commented on src/views/RegisterView.vue
> +            store.setNewUser(newUser as Registered)
Pareil pour le type

2022-07-28 15:48 UTC, Pandazaur commented on src/views/RegisterView.vue
> +            store.users?.filter((user) => {
Pareil: .find or .some peut être plus adapté

2022-07-29 12:29 UTC, kevbesset approved these changes

2022-07-29 12:29 UTC, kevbesset commented on src/components/GlobalNavbar.vue
> +    $color_: #4b494e;
Je serais un peu plus explicite sur les noms de variables + $color_ ça ne veut pas dire grand chose, surtout finit pas "_"

2022-07-29 12:29 UTC, kevbesset commented on src/components/NavbarLink.vue
> +    $border: #4b494e;
pareil ici pour les noms de variables. encore border là ca passe mais color_ je sais pas pk tu mets un `_`

2022-07-29 13:36 UTC, merged